lambda.part2.exercise2 (Klimchuk)
elefus/epam-lab-java8-01-2018 pull request #105
Opened 2018-01-27 10:38 UTC by sysloparich

2018-01-27 10:42 UTC, Duelist256 approved these changes

2018-01-31 16:20 UTC, AlexLuk requested changes

2018-01-31 16:20 UTC, AlexLuk commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        return negate(predicate);
logical operator "!" should be used

2018-01-31 16:20 UTC, AlexLuk commented on src/test/java/lambda/part2/exercise/Exercise2.java
> +        return and(left, right);
logical operator && should be used

2018-02-27 07:49 UTC, denklewer approved these changes

2018-03-09 21:36 UTC, KseniiaIarkova approved these changes

2018-03-12 15:30 UTC, merged