lambda.part1.exercise1 (Ulianov)
elefus/epam-lab-java8-01-2018 pull request #114
Opened 2018-01-28 16:18 UTC by andrulian

2018-01-29 15:37 UTC, AnastasiyaSoloveva approved these changes

2018-01-31 15:52 UTC, AlexLuk requested changes
Fix sortPersonsByAgeUsingArraysSortComparator and sortPersonsByLastNameThenFirstNameUsingArraysSortAnonymousComparator

2018-01-31 15:52 UTC, AlexLuk commented on src/test/java/lambda/part1/exercise/Exercise1.java
> +        Arrays.sort(persons);
custom comparator, working with person age, should be implemented and saved
array should be sorted with use of your custom comparator

2018-01-31 15:52 UTC, AlexLuk commented on src/test/java/lambda/part1/exercise/Exercise1.java
> +                        }
LastName then FirstName compare can be implemented with use of single comparator 
just use if statement inside on it and perform comparing based on firstName if needed

2026-08-19 14:08 UTC, closed without merging