streams.part1.exercise2 (Aliberdov)
elefus/epam-lab-java8-01-2018 pull request #129
Opened 2018-01-29 13:37 UTC by timaliberdov

2018-01-31 17:19 UTC, AlexLuk requested changes

2018-01-31 17:19 UTC, AlexLuk commented on src/test/java/streams/part1/exercise/Exercise2.java
> +            .orElse(0.0D);
orElseThrow is more convenient here

2018-01-31 17:19 UTC, AlexLuk commented on src/test/java/streams/part1/exercise/Exercise2.java
> +            .get();
orElseThrow is more convenient here

2018-01-31 17:19 UTC, AlexLuk commented on src/test/java/streams/part1/exercise/Exercise2.java
> +            .get();
orElseThrow is more convenient here

2018-02-01 13:20 UTC, timaliberdov commented on src/test/java/streams/part1/exercise/Exercise2.java
> +            .get();
Replaced get() with orElseThrow()

2018-03-11 11:43 UTC, AnastasiyaSoloveva approved these changes

2018-03-12 10:04 UTC, Astel approved these changes

2018-05-27 15:28 UTC, closed without merging