streams.part1.exercise1 (Seliukov)
elefus/epam-lab-java8-01-2018 pull request #143
Opened 2018-01-29 21:23 UTC by Duelist256

2018-01-30 09:01 UTC, sysloparich commented on src/test/java/streams/part1/exercise/Exercise1.java
> +                        .distinct()
distinct не нужен, т.к. set

2018-01-30 12:59 UTC, sysloparich approved these changes

2018-01-31 16:46 UTC, AlexLuk requested changes

2018-01-31 16:46 UTC, AlexLuk commented on src/test/java/streams/part1/exercise/Exercise1.java
> +                                .equals("EPAM"))
using stream is redundant here - just first element of collection is needed

2018-02-05 19:57 UTC, Duelist256 commented
@AlexLuk See changes plz

2020-07-11 18:14 UTC, closed without merging